version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    container_name: recipes_api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    depends_on:
      - db
  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    container_name: recipes_client
    command: yarn start
    volumes:
      - ./client:/client
    ports:
      - "4200:4200"
      - "7357:7357"
