version: "3.9"
services:
  db:
    image: postgres
    # volumes:
      # - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      RAILS_ENV: development
      # SECRET_KEY_BASE: 12345678987654321  # For testing production config
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    command: yarn start
    volumes:
      - ./client:/client
    ports:
      - "4200:4200"
      - "7357:7357"
